name: cubancigarinc.com
favicon: null
layout_spectrum: 0.7563
typography_spectrum: 0.74904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#035f81'
    - '#337d99'
    - '#b2ced7'
    - '#609ab0'
  brandStrength: 0.4294909117743373
  lightness: 0.2819546638056636
  saturation: 0.2269104707520455
  rhythmicContrast: 0.18931234255433083
purpose: []
